apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: microservices-app
build:
  artifacts:
  - image: front-end
    context: front-end
    docker:
      dockerfile: Dockerfile
  - image: homerun
    context: HomeRun-Service
    docker:
      dockerfile: Dockerfile
  - image: stats
    context: Stats-Service
    docker:
      dockerfile: Dockerfile
  - image: query
    context: Query-Service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
manifests:
  rawYaml:
  - config/k8s/*
deploy:
  kubectl: {}
